services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_HASH: local
    image: cerebra-ui:local
    pull_policy: never
    environment:
      - STATIC_DIR=/app/static
      - BETTERAUTH_BASE_URL=http://betterauth-service-betterauth-1:4000
      - BETTERAUTH_URL=http://betterauth-service-betterauth-1:4000
      - CORS_ALLOW_ORIGIN=http://localhost:3000
      - WEBUI_SESSION_COOKIE_SAME_SITE=lax
      - WEBUI_SESSION_COOKIE_SECURE=false
      - WEBUI_AUTH=true 
      ### image
      - FAL_KEY=bca68c6c-24f6-4501-b7fb-fa70493969cb:bf3afc9cd3106c456c884ba6d4ab7f5a
      - OPENAI_API_KEY=sk-proj-q7mX9bjvlkvGIvQJgRIPUlpxnnRgihhIPta4GxtS0q2V241e4NmCvwa6hiZZNf37Tc7xjfNARjT3BlbkFJgr1WZy5ri4SA7qsBcwUjbTt9kzUQ9WLiwlKsgMZNt41
      - FAL_MODEL=fal-ai/flux-pro/v1.1
    volumes:
      - ./build:/app/build:ro
      - ./backend:/app/backend:ro
      - ./static:/app/static:ro
    networks:
      - default
      - cerebra_net

networks:
  cerebra_net:
    external: true
