services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_HASH: local
    image: cerebra-ui:local
    pull_policy: never
    environment:
      - STATIC_DIR=/app/static
      - BETTERAUTH_BASE_URL=http://betterauth-service-betterauth-1:4000
      - BETTERAUTH_URL=http://betterauth-service-betterauth-1:4000
      - CORS_ALLOW_ORIGIN=http://localhost:3000
      - WEBUI_SESSION_COOKIE_SAME_SITE=lax
      - WEBUI_SESSION_COOKIE_SECURE=false
      - WEBUI_AUTH=true
      - ENCRYPTION_KEY=sWMJ67yu2VQKjtC2NlMNRXA9hy9TOneLC1Ejn3ZqmjY= 
    volumes:
      - ./build:/app/build:ro
      - ./backend:/app/backend:ro
      - ./static:/app/static:ro
    networks:
      - default
      - cerebra_net
  langflow:
    image: langflowai/langflow:latest
    ports:
      - "7860:7860"     # exposes UI at http://localhost:7860
    environment:
      - LANGFLOW_DATABASE_URL=sqlite:///langflow.db
    volumes:
      - langflow-data:/app/langflow
    networks:
      - default
      - cerebra_net
networks:
  cerebra_net:
    external: true
volumes:
  langflow-data: